using System.Text;
using EjectLens.Models;
using EjectLens.Utils;

namespace EjectLens.Services;

/// <summary>
/// Generates diagnostic report text from collected data.
/// Designed to be safe for clipboard and file export — no private
/// information is intentionally collected, and user paths are redacted.
/// </summary>
public static class ReportService
{
    public static string GenerateReport(ReportModel model)
    {
        var sb = new StringBuilder();

        // Header.
        sb.AppendLine("EjectLens Diagnostic Report");
        sb.AppendLine(new string('=', 60));
        sb.AppendLine($"App Version:    {model.AppVersion}");
        sb.AppendLine($"Windows:        {model.WindowsVersion}");
        sb.AppendLine($"Scan Time:      {model.ScanTime:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Time Range:     {model.TimeRangeDescription}");
        sb.AppendLine($"Selected Drive: {model.SelectedDrive}");
        sb.AppendLine();

        // Section: Matched events.
        sb.AppendLine("── Matched Events ──");
        sb.AppendLine();
        if (model.MatchedEvents.Count == 0)
        {
            sb.AppendLine("  (none)");
        }
        else
        {
            foreach (var evt in model.MatchedEvents)
            {
                AppendEventDetail(sb, evt);
            }
        }
        sb.AppendLine();

        // Section: Possibly related events.
        sb.AppendLine("── Possibly Related Events ──");
        sb.AppendLine();
        if (model.PossiblyRelatedEvents.Count == 0)
        {
            sb.AppendLine("  (none)");
        }
        else
        {
            foreach (var evt in model.PossiblyRelatedEvents)
            {
                AppendEventDetail(sb, evt);
            }
        }
        sb.AppendLine();

        // Section: Unmatched recent events.
        sb.AppendLine("── Unmatched Recent Events (no drive correlation) ──");
        sb.AppendLine();
        if (model.UnmatchedEvents.Count == 0)
        {
            sb.AppendLine("  (none)");
        }
        else
        {
            foreach (var evt in model.UnmatchedEvents)
            {
                AppendEventDetail(sb, evt);
            }
        }
        sb.AppendLine();

        // Section: File lock scan.
        if (!string.IsNullOrEmpty(model.FileLockScanPath))
        {
            sb.AppendLine("── File Lock Scan ──");
            sb.AppendLine();
            sb.AppendLine($"  Scanned path: {PathRedactor.Redact(model.FileLockScanPath)}");

            if (!string.IsNullOrEmpty(model.FileLockError))
            {
                sb.AppendLine($"  Error: {model.FileLockError}");
            }
            else if (model.FileLockResults.Count == 0)
            {
                sb.AppendLine("  No locking processes found.");
            }
            else
            {
                sb.AppendLine($"  Locking processes ({model.FileLockResults.Count}):");
                foreach (var lockInfo in model.FileLockResults)
                {
                    sb.AppendLine($"    - {lockInfo.DisplayName} [{lockInfo.ApplicationType}]");
                }
            }
            sb.AppendLine();
        }

        // Footer.
        sb.AppendLine(new string('=', 60));
        sb.AppendLine("Report generated by EjectLens.");
        sb.AppendLine("This tool is read-only. No processes were terminated.");

        return PathRedactor.RedactFull(sb.ToString());
    }

    private static void AppendEventDetail(StringBuilder sb, EjectBlockEvent evt)
    {
        var status = evt.IsProcessRunning ? "running" : "exited";
        sb.AppendLine($"  [{evt.MatchStatus}] {evt.EventTime:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"  Process:   {evt.ProcessName} (PID {evt.ProcessId}) [{status}]");

        if (!string.IsNullOrEmpty(evt.ApplicationPath))
            sb.AppendLine($"  Path:      {evt.ApplicationPath}");

        if (!string.IsNullOrEmpty(evt.CommandLine))
            sb.AppendLine($"  CmdLine:   {evt.CommandLine}");

        if (!string.IsNullOrEmpty(evt.DeviceInstanceId))
            sb.AppendLine($"  Device:    {evt.DeviceInstanceId}");

        var advisory = ProcessInfoService.GetAdvisoryMessage(
            string.IsNullOrEmpty(evt.ApplicationPath) ? evt.ProcessName : evt.ApplicationPath);

        if (!string.IsNullOrEmpty(advisory))
            sb.AppendLine($"  Note:      {advisory}");

        if (!evt.IsParsed && !string.IsNullOrEmpty(evt.RawMessageSummary))
        {
            sb.AppendLine($"  Raw event message summary:");
            sb.AppendLine($"    {evt.RawMessageSummary}");
        }

        sb.AppendLine();
    }
}
